---
- name: Installing and Launch packetbeat
  hosts: webservers
  become: yes
  tasks:

    # Use command module
  - name: Download packetbeat .deb file
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/packetbeat/packetbeat-7.9.3-amd64.deb

    # Use command module
  - name: Install packetbeat .deb
    command: sudo dpkg -i packetbeat-7.9.3-amd64.deb

    # Copy metricbeat config file
  - name: Drop in packetbeat.yml
    copy:
      src: /etc/ansible/packetbeat/packetbeat.yml
      dest: /etc/packetbeat/packetbeat.yml

    # Setup Packetbeat
  - name: setup packetbeat
    command: packetbeat setup

    # Setup packetbeat service
  - name: Setup packetbeat service
    command: service packetbeat start

    # Enable metricbeat service
  - name: Enable packetbeat service
    systemd:
      name: packetbeat
      enabled: yes
